import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import {
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { parse } from 'yaml';
import {
  GUIDE_QA_FILENAME,
  GuideQaExistsError,
  initGuideQa,
  parseInitQaArgs,
  renderGuideQa,
  runInitQaCli,
} from '../scripts/init-qa.mjs';

const SCRIPT = resolve(import.meta.dirname, '..', 'scripts', 'init-qa.mjs');

const SINGLE_YAML = `# Generated by book-scaffold init-qa.
# Regenerate with: book-scaffold init-qa --force
version: 1
guides:
  - id: book
    check_cmd: npm --offline exec -- book-scaffold qa --format json
`;

const CORPUS_YAML = `# Generated by book-scaffold init-qa.
# Regenerate with: book-scaffold init-qa --force
version: 1
guides:
  - id: llm-app-engineering
    check_cmd: npm --offline exec -- book-scaffold qa --book llm-app-engineering --format json
  - id: evaluation
    check_cmd: npm --offline exec -- book-scaffold qa --book evaluation --format json
`;

const SINGLE_CONFIG = Object.freeze({ corpus: null });
const CORPUS_CONFIG = Object.freeze({
  corpus: Object.freeze({
    books: Object.freeze([
      Object.freeze({ id: 'llm-app-engineering', title: 'LLM App Engineering' }),
      Object.freeze({ id: 'evaluation', title: 'Evaluation' }),
    ]),
  }),
});

function withTempRoot(prefix, callback) {
  const root = mkdtempSync(join(tmpdir(), prefix));
  return Promise.resolve()
    .then(() => callback(root))
    .finally(() => rmSync(root, { recursive: true, force: true }));
}

function captureStream() {
  return {
    value: '',
    write(chunk) {
      this.value += String(chunk);
      return true;
    },
  };
}

test('#158: single-book rendering is exact, stable, valid YAML, and omits --book', () => {
  const first = renderGuideQa(SINGLE_CONFIG);
  const second = renderGuideQa(SINGLE_CONFIG);

  assert.equal(first, SINGLE_YAML);
  assert.equal(second, first);
  assert.doesNotMatch(first, / --book(?:\s|$)/);
  assert.deepEqual(parse(first), {
    version: 1,
    guides: [
      {
        id: 'book',
        check_cmd: 'npm --offline exec -- book-scaffold qa --format json',
      },
    ],
  });
});

test('#158: corpus rendering preserves manifest order and selects each exact id', () => {
  const rendered = renderGuideQa(CORPUS_CONFIG);

  assert.equal(rendered, CORPUS_YAML);
  assert.deepEqual(
    parse(rendered).guides.map((guide) => guide.id),
    ['llm-app-engineering', 'evaluation'],
  );
  assert.match(
    rendered,
    /qa --book llm-app-engineering --format json\n[\s\S]*qa --book evaluation --format json/,
  );
});

test('#158: initGuideQa refuses an existing file before config evaluation', async () => {
  await withTempRoot('book-scaffold-init-qa-existing-', async (root) => {
    const outputPath = join(root, GUIDE_QA_FILENAME);
    writeFileSync(outputPath, 'consumer-owned: true\n');
    writeFileSync(join(root, 'keep.txt'), 'untouched\n');
    let configLoaded = false;

    await assert.rejects(
      initGuideQa({
        projectRoot: root,
        loadConfig: async () => {
          configLoaded = true;
          return SINGLE_CONFIG;
        },
      }),
      (error) => error instanceof GuideQaExistsError && error.code === 'EEXIST',
    );

    assert.equal(configLoaded, false);
    assert.equal(readFileSync(outputPath, 'utf8'), 'consumer-owned: true\n');
    assert.equal(readFileSync(join(root, 'keep.txt'), 'utf8'), 'untouched\n');
  });
});

test('#158: --force replaces only guide_qa.yaml and is byte-deterministic', async () => {
  await withTempRoot('book-scaffold-init-qa-force-', async (root) => {
    const outputPath = join(root, GUIDE_QA_FILENAME);
    writeFileSync(outputPath, 'consumer-owned: true\n');
    writeFileSync(join(root, 'keep.txt'), 'untouched\n');

    const options = {
      projectRoot: root,
      force: true,
      loadConfig: async (receivedRoot) => {
        assert.equal(receivedRoot, root);
        return CORPUS_CONFIG;
      },
    };
    const first = await initGuideQa(options);
    const second = await initGuideQa(options);

    assert.equal(first.path, outputPath);
    assert.deepEqual(first.guideIds, ['llm-app-engineering', 'evaluation']);
    assert.equal(first.contents, CORPUS_YAML);
    assert.equal(second.contents, first.contents);
    assert.equal(readFileSync(outputPath, 'utf8'), CORPUS_YAML);
    assert.equal(readFileSync(join(root, 'keep.txt'), 'utf8'), 'untouched\n');
    assert.deepEqual(readdirSync(root).sort(), [GUIDE_QA_FILENAME, 'keep.txt']);
  });
});

test('#158: direct CLI creates the implicit single-book file without other writes', async () => {
  await withTempRoot('book-scaffold-init-qa-single-', (root) => {
    const result = spawnSync(process.execPath, [SCRIPT], {
      cwd: root,
      encoding: 'utf8',
      timeout: 10_000,
    });

    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, `init-qa: wrote ${GUIDE_QA_FILENAME}\n`);
    assert.equal(result.stderr, '');
    assert.equal(readFileSync(join(root, GUIDE_QA_FILENAME), 'utf8'), SINGLE_YAML);
    assert.deepEqual(readdirSync(root), [GUIDE_QA_FILENAME]);
  });
});

test('#158: direct CLI resolves every corpus book from consumer config', async () => {
  await withTempRoot('book-scaffold-init-qa-corpus-', (root) => {
    writeFileSync(
      join(root, 'astro.config.mjs'),
      `export default {
  integrations: [{
    name: 'book-scaffold-astro',
    __bookScaffoldResolvedConfig: {
      preset: 'minimal',
      corpus: {
        __bookCorpusVersion: 1,
        preset: 'minimal',
        books: [
          { id: 'llm-app-engineering', title: 'LLM App Engineering' },
          { id: 'evaluation', title: 'Evaluation' },
        ],
      },
    },
  }],
};
`,
    );

    const result = spawnSync(process.execPath, [SCRIPT], {
      cwd: root,
      encoding: 'utf8',
      timeout: 10_000,
    });

    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, `init-qa: wrote ${GUIDE_QA_FILENAME}\n`);
    assert.equal(result.stderr, '');
    assert.equal(readFileSync(join(root, GUIDE_QA_FILENAME), 'utf8'), CORPUS_YAML);
  });
});

test('#158: help and invalid arguments are non-mutating contract branches', async () => {
  await withTempRoot('book-scaffold-init-qa-args-', async (root) => {
    let configLoads = 0;
    const loadConfig = async () => {
      configLoads += 1;
      return SINGLE_CONFIG;
    };

    const helpOut = captureStream();
    const helpErr = captureStream();
    assert.equal(
      await runInitQaCli({
        argv: ['--help'],
        projectRoot: root,
        stdout: helpOut,
        stderr: helpErr,
        loadConfig,
      }),
      0,
    );
    assert.match(helpOut.value, /^Usage: book-scaffold init-qa/);
    assert.equal(helpErr.value, '');

    const invalidOut = captureStream();
    const invalidErr = captureStream();
    assert.equal(
      await runInitQaCli({
        argv: ['--book', 'evaluation'],
        projectRoot: root,
        stdout: invalidOut,
        stderr: invalidErr,
        loadConfig,
      }),
      2,
    );
    assert.equal(invalidOut.value, '');
    assert.match(invalidErr.value, /unknown argument "--book"/);
    assert.equal(configLoads, 0);
    assert.deepEqual(readdirSync(root), []);
  });
});

test('#158: argument parser rejects duplicate force flags', () => {
  assert.deepEqual(parseInitQaArgs([]), { force: false, help: false });
  assert.deepEqual(parseInitQaArgs(['--force']), { force: true, help: false });
  assert.throws(
    () => parseInitQaArgs(['--force', '--force']),
    /--force may be specified only once/,
  );
});
